### ISSUE TITLE
Support matching maps

### ISSUE THREAD

**Issue by nietaki** [nietaki/rexbug#30]
Will require a fix in `:redbug`, see https://github.com/massemanet/redbug/issues/2

See also https://github.com/nietaki/rexbug/issues/13

**Comment by massemanet** [comment]
(possibly) fixed in redbug 0bc3ffa
please feel free to verify.

**Comment by nietaki** [comment]
Brilliant! I'll have a look this weekend.

**Comment by massemanet** [comment]
try 935ae87 instead. allows binding of vars in maps;

```
redbug:start("maps:to_list(#{a=>#{b:=B}})when B==1")
```

**Comment by nietaki** [comment]
I played around with it and it works great. 

When you release a new version on hex.pm I'll make sure rexbug uses it and does the right thing with maps as well.

**Comment by massemanet** [comment]
I'll update the docs and release it as 1.2.0. Thanks for your help.

**Comment by massemanet** [comment]
redbug 1.2.0 is now on hex.pm.

**Comment by nietaki** [comment]
It is indeed. I'll fix this issue on this weekend the latest.

**Comment by nietaki** [comment]
Closed by https://github.com/nietaki/rexbug/pull/31
