### ISSUE TITLE
print_msec option doesn't work

### ISSUE THREAD

**Issue by redpublic** [nietaki/rexbug#33]
Seems like print_msec option doesn't affect output format:

```
iex(44)> Rexbug.start("Map.take/2 :: return", msgs: 10, print_msec: true, arity: true)
{333, 1}
iex(45)> Map.take(%{a: 1}, [:a])
%{a: 1}

# 01:43:16 #PID<0.554.0> IEx.Evaluator.init/4
# Map.take/2

# 01:43:16 #PID<0.554.0> IEx.Evaluator.init/4
# Map.take/2 -> %{a: 1}
```

**Comment by nietaki** [comment]
Sorry for the late reply.

Good spot, I'm going to have a fix soon.

**Comment by nietaki** [comment]
Should be fixed in https://hex.pm/packages/rexbug/1.0.2, let me know if there's any problems @redpublic, I should be more on top of it this time around :)
