### ISSUE TITLE
Is it possible to use Rexbug to trace messages send/received by processes?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [nietaki/rexbug#34]
Background
---
We have an app the keeps running. This is a OTP application that has other OTP applications as dependencies. It uses GenServers and Supervisors as do many of its dependencies.

Problem
-----

The app doesn’t crash, but it constantly prints the following error:

=ERROR REPORT==== 14-Jun-2019::14:31:35.089496 ===
Unexpected message: {#Ref<0.2607974300.3493068808.175359>,badarg}

Rexbug?
---

I was told about this library, but after reading the README page I could not find any examples of message tracing between processes. I know Rexbug is a wrapper for the erlang counterpart, but I am not familiar with it either. 

Can this library help me in my task? Is it suitable for our use case?

**Comment by nietaki** [comment]
It is possible to do it with Rexbug! Here's an example:

```elixir
iex(1)> s = self()  
#PID<0.193.0>
iex(2)> proc = Process.spawn(fn ->                    
...(2)>   receive do                             
...(2)>     anything -> send(s, {:got, anything})
...(2)>   end                                    
...(2)> end, [])
iex(3)> Rexbug.start([:send, :receive], procs: proc, time: 60_000) 
{1, 0}
iex(4)> send(proc, :foo)
:foo
        
# 18:31:08 #PID<0.208.0> (:dead)
# <<< :foo
        
# 18:31:08 #PID<0.208.0> (:dead)
# #PID<0.193.0> IEx.Evaluator.init/4 <<< {:got, :foo}
iex(5)> flush()
{:got, :foo}
:ok
redbug done, timeout - 2
```

I'm probably going to add this example to the README

**Comment by ghost** [comment]
> It is possible to do it with Rexbug! Here's an example:
> 
> ```elixir
> iex(1)> s = self()  
> #PID<0.193.0>
> iex(2)> proc = Process.spawn(fn ->                    
> ...(2)>   receive do                             
> ...(2)>     anything -> send(s, {:got, anything})
> ...(2)>   end                                    
> ...(2)> end, [])
> iex(3)> Rexbug.start([:send, :receive], procs: proc, time: 60_000) 
> {1, 0}
> iex(4)> send(proc, :foo)
> :foo
>         
> # 18:31:08 #PID<0.208.0> (:dead)
> # <<< :foo
>         
> # 18:31:08 #PID<0.208.0> (:dead)
> # #PID<0.193.0> IEx.Evaluator.init/4 <<< {:got, :foo}
> iex(5)> flush()
> {:got, :foo}
> :ok
> redbug done, timeout - 2
> ```
> 
> I'm probably going to add this example to the README

This trick is handy - must share
