### ISSUE TITLE
Needs the ability to be able to trace on is_struct or by pattern matching map fields

### ISSUE THREAD

**Issue by bhuntpenn** [nietaki/rexbug#53]
Redbug 2 has support for map fields matching now, https://github.com/massemanet/redbug/blob/master/src/redbug_parser.yrl#L8 , but I can't figure out how to get redbug to match on Elixir module names.

**Comment by bhuntpenn** [comment]
For reference - https://github.com/massemanet/redbug/issues/21

**Comment by nietaki** [comment]
Implemented in the `v2` branch, see the tests for examples: https://github.com/nietaki/rexbug/commit/5d5ed66ca5e5541e7e6ee88116a8b39669c2965f#diff-7abe3feae8043a5dcfe0c3da525814e1780a889d35ecfbe1f68624f08612f219R139-R147

I'm going to close this for now, feel free to reopen if needed
